In [1]:
2+2

4

In [1]:
new_list=[2,4,5]
new_list[2]

5

In [5]:
arr=np.array([2,3,4])
arr

array([2, 3, 4])

In [3]:
import numpy as np

In [4]:
arr

NameError: name 'arr' is not defined

In [13]:
height=[56,73,93,90,27]
weight=[90,74,53,83,24]

arr_height=np.array(height)
arr_weight=np.array(weight)

In [14]:
arr_height

array([56, 73, 93, 90, 27])

In [12]:
arr_height

NameError: name 'arr_height' is not defined

In [15]:
bmi=arr_height/arr_weight
bmi

array([ 0.62222222,  0.98648649,  1.75471698,  1.08433735,  1.125     ])

In [16]:
h=[2,5,6]
w=[4,5,6]

hw=h+w
hw

[2, 5, 6, 4, 5, 6]

In [17]:
w=np.array(hw)

w

array([2, 5, 6, 4, 5, 6])

In [21]:
hr=np.array(h)
hr

array([2, 5, 6])

In [24]:
t=[4,5,6]
tr=np.array(t)
tr

array([4, 5, 6])

In [25]:
result=tr/hr
result

array([ 2.,  1.,  1.])

In [31]:
np.arange(1,100,20)

array([ 1, 21, 41, 61, 81])

In [36]:
tr>2

array([ True,  True,  True], dtype=bool)

In [37]:
tr

array([4, 5, 6])

In [39]:
tr[tr>4]

array([5, 6])

In [40]:
okj=np.array([[2,6,7,9],[8,2,5,8]])
okj

array([[2, 6, 7, 9],
       [8, 2, 5, 8]])

In [41]:
type(okj)

numpy.ndarray

In [47]:
okj[1][3]

8

In [48]:
okj[0,1]

6

In [64]:
okj[1][1:]#select an array from a specific point to the end

array([2, 5, 8])

In [67]:
okj[0][1:]

array([6, 7, 9])

In [69]:
np.mean(okj[0][1:])# To calcute the mean of values in a given range

7.333333333333333

In [71]:
np.median(okj[0][1:])

7.0

In [72]:
np.random.rand(3,4)

array([[ 0.56494432,  0.16144256,  0.15391313,  0.95269837],
       [ 0.580323  ,  0.07035682,  0.26290007,  0.49065754],
       [ 0.60041203,  0.83939074,  0.50389448,  0.30926471]])

In [73]:
okj.shape

(2, 4)

In [74]:
np.random.choice(7)

6

In [81]:
np.random.seed(4)


In [83]:
np.random.rand(3,4)

array([[ 0.96702984,  0.54723225,  0.97268436,  0.71481599],
       [ 0.69772882,  0.2160895 ,  0.97627445,  0.00623026],
       [ 0.25298236,  0.43479153,  0.77938292,  0.19768507]])

In [88]:
np.random.seed(4)

In [92]:
hello=np.random.rand(4,2)
hello

array([[ 0.25298236,  0.43479153],
       [ 0.77938292,  0.19768507],
       [ 0.86299324,  0.98340068],
       [ 0.16384224,  0.59733394]])

In [90]:
okj

array([[2, 6, 7, 9],
       [8, 2, 5, 8]])

In [95]:
result=np.dot(hello,okj)
result

array([[  3.98429698,   2.38747724,   3.9448342 ,   5.75517352],
       [  3.14024644,   5.07166768,   6.44410583,   8.59592689],
       [  9.59319189,   7.14476077,  10.95795604,  15.63414454],
       [  5.10635603,   2.17772134,   4.13356541,   6.25325172]])

In [96]:
result[3][:1]

array([ 5.10635603])

In [97]:
np.matmul(hello,okj)

array([[  3.98429698,   2.38747724,   3.9448342 ,   5.75517352],
       [  3.14024644,   5.07166768,   6.44410583,   8.59592689],
       [  9.59319189,   7.14476077,  10.95795604,  15.63414454],
       [  5.10635603,   2.17772134,   4.13356541,   6.25325172]])

In [98]:
np.sum(okj)

47

In [99]:
np.sqrt(9)

3.0

In [100]:
np.square(3)

9

In [102]:
np.sin(60)

-0.30481062110221668

In [104]:
np.max(hello)

0.98340067717531277

In [105]:
np.corrcoef(okj)#this to check the relationship of datas given

array([[ 1.        , -0.11826248],
       [-0.11826248,  1.        ]])

In [108]:
np.arcsin(-0.30481062110221668)

-0.30973958179392846

In [110]:
np.random.seed(4)

In [112]:
np.random.rand(2)

array([ 0.43614665,  0.94897731])

In [5]:
import numpy as np

In [6]:
val=np.random.randint(9,size=9)

In [7]:
val

array([5, 0, 3, 8, 1, 5, 7, 4, 0])

In [8]:
val[val%2==1]#This return all the old number from the randomly generated integers

array([5, 3, 1, 5, 7])

In [9]:
val[val%2==1]=50#This line replaces all odd numbers from the randomly generated integers with 50

In [10]:
val

array([50,  0, 50,  8, 50, 50, 50,  4,  0])